echo "Тест 1: Проверка передачи недостающих аргументов"
/script.sh -i test.txt
if [ $? -eq 1 ] && [[ $(tail -n 1 output.txt) == "" ]];
then
    echo "Успешно: скрипт завершился с ошибкой и выходной файл пустой"
else
    echo "Ошибка: получен неверный результат"
fi
